name: Deploy app to AWS Amplify
on:
  pull_request:  
    types: 
      - closed
    branches: 
      - main
  push:
    branches: 
      - main

# permissions: 
#   contents: read
  # id-token: write

jobs:
  checkout:
    runs-on: ubuntu-latest
    environment: Production
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
  
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli
  
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Config AWS credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Build
        run: yarn build
      
      - name: Amplify Pull
        run: |
          amplify pull \
            --amplify "{\"projectName\":\"mijo\", \"appId\": \"${AMPLIFY_APP_ID}\",\"envName\":\"prod\",\"defaultEditor\":\"code\"}"  \
            --providers "{\"awscloudformation\":{\"configLevel\":\"project\",\"useProfile\":false,\"accessKeyId\":\"${AWS_ACCESS_KEY_ID}\",\"secretAccessKey\":\"${AWS_SECRET_ACCESS_KEY}\",\"region\":\"${AWS_REGION}\"}}"  \
            --categories "{\"storage\":{\"region\": \"${AWS_REGION}\",\"bucketName\":\"${AWS_BUCKET_NAME}\"}}"  \
            --yes
        env:
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Check .amplify folder existence
        id: isInitiated
        env:
          FILE: .amplify
        shell: bash
        run: |
          if [[ -f $FILE ]]; then
            echo ".amplify exists"
            echo "AMPLIFY_PATH=true" >> "$GITHUB_OUTPUT"
          else
            echo ".amplify non-exists"
            echo "AMPLIFY_PATH=false" >> "$GITHUB_OUTPUT"
          fi 

      - name: Amplify init
        if: steps.isInitiated.outputs.AMPLIFY_PATH == 'false'
        run: |
          amplify init \
            --amplify "{\"projectName\":\"mijo\", \"appId\": \"${AMPLIFY_APP_ID}\",\"envName\":\"prod\",\"defaultEditor\":\"code\"}"  \
            --providers "{\"awscloudformation\":{\"configLevel\":\"project\",\"useProfile\":false,\"accessKeyId\":\"${AWS_ACCESS_KEY_ID}\",\"secretAccessKey\":\"${AWS_SECRET_ACCESS_KEY}\",\"region\":\"${AWS_REGION}\"}}"  \
            --categories "{\"storage\":{\"region\": \"${AWS_REGION}\",\"bucketName\":\"${AWS_BUCKET_NAME}\"}}"  \
            --yes
        env:
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Upload .next to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
          source_dir: '.next'
          destination_dir: '.next'
      
      # Only push Backend
      # - name: Amplify push
      #   run: |
      #     amplify push -y

      # - name: Deploy to Amplify
      #   run: |
      #     aws amplify start-deployment \
      #       --app-id ${{ secrets.AMPLIFY_APP_ID }} \
      #       --branch-name ${{ secrets.AMPLIFY_BRANCH_NAME }} \
      #       --region ${{ vars.AWS_REGION }}

    
