name: Develop Deployment
on:
  push:
    branches: 
      - develop

jobs:
  develop:
    runs-on: ubuntu-latest
    environment: Develop
    env: # Env variables needed during build
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ vars.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'npm'

    - name: Install yarn
      run: npm install --global yarn

    - name: Install dependencies
      run: yarn install

    - name: Build project artifacts
      run: yarn build
      

      