name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy to Vercel
        uses: ./.github/actions/vercel/action.yml
        with:
          environment: 'production'
          organizationID: ${{ secrets.VERCEL_ORG_ID }}
          projectID: ${{ secrets.VERCEL_PROJECT_ID }}
          token: ${{ secrets.VERCEL_TOKEN }}
